### ISSUE TITLE
Enter DAO and vote in one click

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#131]
**Is your feature request related to a problem? Please describe.**
To improve the experience, we would like to make joining a DAO seamless for the user. Right now, the user is required to click twice: first to join a DAO and then to make his vote. We would like to make both actions with a single button click.

**Describe the solution you'd like**
The user that wants to vote on a proposal from a public treasury would be able to join and vote with a single click.
If the treasury is private, no button should be displayed.  The message `You can't join a private DAO` in the place of the button would help clarify why.

**Comment by Viterbo** [comment]
@karynemayer, 

This implementation was made and reverted because I was getting an unknown error (described [here](https://github.com/telosnetwork/app-telos-native/issues/92#issuecomment-1255382749)) so I made the current two steps button as a temporal solution.

Now I know the error I was getting was right and that was I had zero token in staking. User must have positive amount of token in staking to vote. So I can easelly return to the first approach but still don't know how should I handle the fact that the user has no staking tokens.

What should the buttons say?
Should it redirect the user to https://wallet.telos.net/ ?

**Comment by karynemayer** [comment]
@Viterbo 
The error handling is outside the scope of this task. It seems that #130 is being developed by @DevArtemNuss, and it should impact the error message you're talking about as well.

Once we have the error messages displayed in a human-readable format, we can think about how to make them more helpful.
